import { mkdir, writeFile } from 'node:fs/promises'
import { join, relative } from 'node:path'
import { generateManifest } from '@theoven/core'
import { boolFlag, type ParsedArgs, stringFlag } from '../args'
import { CANDIDATES, resolveEntry, resolveRoot, resolveRoutesDir } from '../paths'
import { BANNER, fail, info, style, success } from '../ui'

/**
 * `oven build`.
 *
 * Two jobs, in order:
 *
 *   1. Write a route manifest with static imports, so production neither walks the filesystem at
 *      boot nor hides route modules from the bundler.
 *   2. Bundle with `Bun.build`, targeting Bun.
 *
 * The order matters: the manifest must exist before bundling, or the bundler cannot see the
 * route modules it imports and they end up outside the bundle.
 */
export async function build(args: ParsedArgs): Promise<number> {
  const root = resolveRoot()
  const entry = resolveEntry(root, stringFlag(args.flags, 'entry'))

  if (!entry) {
    fail(
      'No entry file found.',
      `Looked for ${CANDIDATES.entry.join(', ')}. Pass one with --entry <path>.`,
    )
    return 1
  }

  const outdir = join(root, stringFlag(args.flags, 'outdir', 'dist') ?? 'dist')
  const minify = boolFlag(args.flags, 'minify', true)
  const sourcemap = boolFlag(args.flags, 'sourcemap', true)

  info(`${BANNER} ${style.dim('build')}`)

  const routesDir = resolveRoutesDir(root, stringFlag(args.flags, 'routes'))
  let bundleEntry = entry

  if (routesDir) {
    const manifestDir = join(root, '.oven')
    const manifestPath = join(manifestDir, 'routes.ts')
    const entryPath = join(manifestDir, 'entry.ts')

    await mkdir(manifestDir, { recursive: true })
    await writeFile(manifestPath, await generateManifest(routesDir, manifestDir))

    // The bundle has no routes directory to walk, so a generated entry installs the manifest
    // before the app module runs. `loadRoutes` then uses it instead of touching the filesystem,
    // which means the app's own code is identical in development and production — the only way
    // the two stay in agreement.
    const entryImport = `./${relative(manifestDir, entry).split('\\').join('/')}`
    await writeFile(
      entryPath,
      [
        '// Generated by `oven build`. Do not edit.',
        '//',
        '// Installs the route manifest, then hands over to the real entry. Without this the',
        '// bundle would look for a routes directory that only exists in the source tree.',
        "import { setRouteManifest } from '@theoven/core'",
        "import { registerRoutes } from './routes'",
        '',
        'setRouteManifest(registerRoutes)',
        '',
        `await import('${entryImport}')`,
        '',
      ].join('\n'),
    )

    bundleEntry = entryPath
    success(`route manifest  ${style.dim(relative(root, manifestPath))}`)
  }

  const started = Bun.nanoseconds()

  const result = await Bun.build({
    entrypoints: [bundleEntry],
    outdir,
    target: 'bun',
    minify,
    sourcemap: sourcemap ? 'linked' : 'none',
    naming: '[dir]/index.[ext]',
    // Bun runs the output, so its own built-ins must not be inlined.
    external: ['bun', 'bun:*'],
  })

  if (!result.success) {
    fail('Build failed.')
    for (const log of result.logs) console.error(`  ${log.message}`)
    return 1
  }

  const elapsed = (Bun.nanoseconds() - started) / 1e6
  let total = 0

  for (const artifact of result.outputs) {
    const size = artifact.size ?? 0
    total += size
    success(`${relative(root, artifact.path)}  ${style.dim(`${(size / 1024).toFixed(1)} KB`)}`)
  }

  info('')
  info(
    style.dim(
      `  ${result.outputs.length} file(s), ${(total / 1024).toFixed(1)} KB in ${elapsed.toFixed(0)}ms`,
    ),
  )
  info(style.dim('  run it with `oven start`'))
  return 0
}
